#include "r_cg_macrodriver.h"
#include "r_cg_port.h"
#include "r_cg_userdefine.h"

void R_PORT_Create(void)
{
    PORT.PSRB.BYTE = _00_PORT_PSEL0_PB0;

    PORT4.PMR.BYTE = 0x00U;
    PORT4.PDR.BYTE = _01_Pm0_MODE_OUTPUT | _00_Pm1_MODE_INPUT | _00_Pm2_MODE_INPUT | _00_Pm6_MODE_INPUT | _B8_PDR4_DEFAULT;

	PORTA.PMR.BYTE = 0x00U;
    PORTA.PDR.BYTE = _02_Pm1_MODE_OUTPUT | _08_Pm3_MODE_OUTPUT | _40_Pm6_MODE_OUTPUT | _A5_PDRA_DEFAULT;

	PORTB.PMR.BYTE = 0x00U;
    PORTB.PDR.BYTE = _01_Pm0_MODE_OUTPUT | _D4_PDRB_DEFAULT;

	PORTC.PMR.BYTE = 0x00U;
    PORTC.PDR.BYTE = _80_Pm7_MODE_OUTPUT;

	PORTE.PMR.BYTE = 0x00U;
    PORTE.PDR.BYTE = _02_Pm1_MODE_OUTPUT | _80_Pm7_MODE_OUTPUT | _60_PDRE_DEFAULT;

	PORTJ.PMR.BYTE = 0x00U;
    PORTJ.PDR.BYTE = _80_Pm7_MODE_OUTPUT | _3F_PDRJ_DEFAULT;
}
